#!/usr/bin/bash
#
#
# Copyright 2017 Ronald Dahlgren <ronald.dahlgren@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

declare -r thisversion='1'
declare -r thisscript='gtk-bootstrap'

DEFAULT_VERSION=0.0.1
DEFAULT_EMAIL=missing@missing.missing
DEFAULT_DOMAIN=missing.missing

function print_usage {
  echo "${thisscript} verson ${thisversion}"
  echo
  echo "Creates a templated gtk3 project using autotools as a build system."
  echo
  echo "Usage:"
  echo "  ${thisscript} PROJECT_NAME PROJECT_DIRECTORY [PROJECT_EMAIL] [PROJECT_DOMAIN] [PROJECT_VERSION]"
  echo ""
  echo "Example: "
  echo "  ${thisscript} spreadsheet /work/spreadsheet/ bugs@spreadsheet.org http://spreadsheet.org 1.0.0"
}

if [ $# -gt 5 -o $# -lt 2 -o "$1" = -h -o "$1" = --help ]
then
  print_usage
  exit 1
fi

PROJECT_NAME=$1
PROJECT_DIRECTORY=$2

PROJECT_EMAIL=${3:-$DEFAULT_EMAIL}
PROJECT_DOMAIN=${4:-$DEFAULT_DOMAIN}
PROJECT_VERSION=${5:-$DEFAULT_VERSION}

# Copy all the templated files over
cp -Rv template-files $PROJECT_DIRECTORY
# Substitute placeholders
sed -iv "s/__PROJECT_NAME__/$PROJECT_NAME/g; s/__PROJECT_VERSION__/$PROJECT_VERSION/g; s/__PROJECT_EMAIL__/$PROJECT_EMAIL/g; s/__PROJECT_DOMAIN__/$PROJECT_DOMAIN/g" ${PROJECT_DIRECTORY}/configure.ac
